### ISSUE TITLE
TaxServiceRest::getTax produces PHP notice when using "summary mode".

### ISSUE THREAD

**Issue by maorcatmyheritage** [avadev/AvaTax-Calc-REST-PHP#16]
The reason is that the response doesn't contain TaxDetails but the code in /Volumes/mhdev/working-copies/web/trunk/vendor/avalara/avatax/src/AvaTax/GetTaxResult.php:98 calls \AvaTax\TaxDetail::parseTaxDetails which loops through $object->TaxDetails without checking for existence.

**Comment by anyarms** [comment]
Fixed!
