### ISSUE TITLE
Request: Add more control over the HTTP request and response

### ISSUE THREAD

**Issue by maorcatmyheritage** [avadev/AvaTax-Calc-REST-PHP#17]
This is a request, not a bug:
The requests below refer to \AvaTax\TaxServiceRest::getTax() function.
1. The code doesn't give option to set some important HTTP request params, such as timeout. This can be very useful.
2. The code doesn't check the response and status codes in case of error and doesn't return it to the caller. Thus, we don't have any option to handle errors (error due timeout, bad request, etc)

**Comment by skylord123** [comment]
I fixed the second thing you mentioned inside of #33 

I am looking into a good way to do the first thing.

**Comment by skylord123** [comment]
Alright, I modified my PR to add in the ability to define custom cURL options.

PR: https://github.com/avadev/AvaTax-Calc-REST-PHP/pull/33
commit: a55f5bcc59cf2e8d0c7f20dc9d61a4c8e7725d9a
