### ISSUE TITLE
AvaTax/GetTaxRequest.php sets default timezone to UTC w/o returning it back to orig timezone

### ISSUE THREAD

**Issue by nomaddesign** [avadev/AvaTax-Calc-REST-PHP#22]
When GetTaxRequest.php sets PHP DEFAULT time zone to UTC on line 43 it never returns it back to original timezone.   This creates all kinds havoc in our ecommerce application... Please use a less heavy-handed way to set timezone -or- at least return to original timezone when done.   

Something like... 
$originalZone = date_default_timezone_get();
date_default_timezone_set('UTC');
... avalara code...
date_default_timezone_set($originalZone);

**Comment by anyarms** [comment]
Resolved!
