### ISSUE TITLE
library shares composer package name with SOAP library

### ISSUE THREAD

**Issue by shieldo** [avadev/AvaTax-Calc-REST-PHP#27]
I know this is just an example library for making use of the REST API, but it shares the same package name in its `composer.json` file as the SOAP library https://github.com/avadev/AvaTax-Calc-SOAP-PHP.git (and indeed Packagist gives that one precedence).  Is it worth giving this one a different name (like `avalara/avatax-rest`) so it can exist in Packagist separately or is it your opinion that this is only example code?

**Comment by skylord123** [comment]
Opened a pull request for this. I would like to be able to use composer without specifying the repository location to identify between the two.

**Comment by shieldo** [comment]
Hey @anyarms - is this library still being maintained? :)
