### ISSUE TITLE
Error: First parameter must either be an object or the name of an existing class

### ISSUE THREAD

**Issue by shiloanton** [avadev/AvaTax-Calc-REST-PHP#31]
Again there was an error in your code.

File: AvaTax/GetTaxResult.php

![error_avatax](https://cloud.githubusercontent.com/assets/18698321/18045587/34bab43e-6ddc-11e6-930d-3be63734f3a0.png)

**Comment by skylord123** [comment]
This happened if the response from the cURL request didn't return anything. I created a PR that fixes this in #33

**Comment by skylord123** [comment]
Instead of just erroring out, my PR will throw an exception with a more detailed message. This way you can catch the error and handle it in code.

**Comment by TkachukRuslan** [comment]
Hi
Could you please update the status of this issue
Waiting your response.

**Comment by TkachukRuslan** [comment]
Hi,
We have gotten similar exception 5 minits ago.
http://clip2net.com/s/3CbwbTn

Do you have any updates of fixing it ?

**Comment by TkachukRuslan** [comment]
@skylord123 
@bartkamphuis 
@shieldo 
@shrimpwagon 

Partners we have many exceptions from the test and several from the production
http://clip2net.com/s/3CbwbTn

Could you investigate this issue and fixed this in near time
Thank you with advance for the fast answer

**Comment by shrimpwagon** [comment]
You need to test to make sure that the json got encoded properly:

https://github.com/avadev/AvaTax-Calc-REST-PHP/blob/master/src/AvaTax/GetTaxResult.php#L58

The server probably failed.

Post the rest of your code. What was the server response?

**Comment by shrimpwagon** [comment]
Here's your problem:

https://github.com/avadev/AvaTax-Calc-REST-PHP/blob/master/src/AvaTax/TaxServiceRest.php#L140

There is zero server response verification. Need to make sure that it was a 200 HTTP response and that the response is proper JSON format.

**Comment by TkachukRuslan** [comment]
@shrimpwagon 
We do not note Ajax requests. Commits are normally.

**Comment by shrimpwagon** [comment]
@TkachukRuslan 
You can still write an entry to a db table with the data transactions between your server and Avalara's.
